config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

 def create
    @flat = Flat.new(flat_params)
    @flat.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :descriptoin, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="container">
  <div class="row">
    <% @flats.each do |flat| %>
    <div class="col-4 mt-4">
      <div class="flat-card">
        <div class="flat-card-content">
          <%= flat.name %>
          <%= flat.description %>
          <div class="flex">
            <div class="flex">
              <i class="material-icons mr-2">people</i>
              <span><%= flat.number_of_guests%></span>
            </div>
            <div class="flex ml-3">
              <i class="material-icons mr-2">euro_symbol</i>
              <span><%= flat.price_per_night%></span>
            </div>
          </div>
        </div>
        <div class="card-footer">
          Footer
        </div>
      </div>
    </div>
  <% end %>
  </div>
</div>

<!--


 <div class="col-sm card-footer">
      <p>More infor</p>
  </div>
 -->

app/views/flats/new.html.erb
<%= form_for(@flat) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :number_of_guests %>
  <%= f.number_field :number_of_guests %>
  <%= f.label :price_per_night %>
  <%= f.number_field :price_per_night %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>

    <nav class="navbar navbar-light bg-light">
      <a class="navbar-brand" href="#">Simple Airbnb</a>
      <%= link_to 'New Listing', new_flat_path %> |
    </nav>

    <%= yield %>
  </body>
</html>